# Generated by Django 4.1.3 on 2022-12-05 00:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_vendedor_delete_producto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreProducto', models.CharField(max_length=200)),
                ('votes', models.IntegerField(default=0)),
                ('nombreVendedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.vendedor')),
            ],
        ),
    ]
