# Generated by Django 4.1.3 on 2022-12-05 00:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_producto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='votes',
            new_name='cantidad',
        ),
    ]
